apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-etcd-shield-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: etcd_shield_alerts
      interval: 1m
      rules:

      - alert: EtcdShield
        expr: |
          etcd_shield_alert_triggered > 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: >-
             Etcd Shield Alert Triggered
          description: >-
             Etcd Shield Alert Triggered in cluster {{ $labels.source_cluster }}.
          alert_team_handle: >-
            <!subteam^S07SW2EEW3D> <!subteam^S05Q1P4Q2TG>
          runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/infra/etcd.md
          slo: "true"
